#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/windrose-bootstrap-shared"

main() {
  info "Running windrose-bootstrap"
  prepareWindroseAppFolders
  updateWindroseServerConfig

  # no proton bootstrap needed

  initCrontab
  bootstrapHook
  supervisorctl start windrose-updater
  info "Bootstrap complete"
}

main
