[supervisord]
user=root
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor

[unix_http_server]
file=/dev/shm/supervisor.sock
chmod=0755
chown=windrose:windrose
username=dummy
password=dummy

[supervisorctl]
serverurl=unix:///dev/shm/supervisor.sock
username=dummy
password=dummy

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:crond]
user=root
environment=HOME="/root",USER="root",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/sbin/cron -f
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=true
autorestart=true
priority=20

[program:windrose-bootstrap]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-bootstrap
directory=/home/windrose
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=true
autorestart=false
startsecs=0
startretries=0
priority=30

[program:windrose-server]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-server
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=false
autorestart=true
startsecs=10
startretries=10
stopwaitsecs=90
priority=100

[program:windrose-updater]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-updater
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=false
autorestart=false
startsecs=0

[program:windrose-backup]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-backup
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=false
autorestart=false
startsecs=0

[program:windrose-restart]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-restart
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=false
autorestart=false
startsecs=0

[program:windrose-force-update]
user=windrose
environment=HOME="/home/windrose",USER="windrose",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/local/etc/windrose/windrose-force-update
stdout_syslog=true
stderr_syslog=true
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
autostart=false
autorestart=false
startsecs=0

[include]
files = /usr/local/etc/supervisor/conf.d/*.conf
