#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

windrose_server_pid=-1
timeout=60
kill_signal=INT

cd "$install_path" || fatal "Could not cd $install_path"
windrose_server="$install_path/$windrose_binary_path"

main() {
  waitForServerDownload
  runServer
}

waitForServerDownload() {
  while :; do
    if [ -f "$windrose_server" ]; then
      break
    else
      debug "windrose Server is not yet downloaded - waiting"
      sleep 7
    fi
  done
}

runServer() {
  info "Running windrose-server"
  debug "Server config ServerName:$SERVER_NAME - ServerQueryPort:${SERVER_QUERYPORT:-15637}"

  export WINEPREFIX=$WINEPREFIX
  export WINEARCH=$WINEARCH
  export WINEPATH=$WINEPATH
  export WINEDEBUG=$WINEDEBUG

  chmod +x "$windrose_server"
  wine "$windrose_server" &
  windrose_server_pid=$!
  echo $windrose_server_pid >"$windrose_server_pidfile"

  wait $windrose_server_pid
  debug "windrose-server with PID $windrose_server_pid stopped"


  cleanup
  info "Shutdown complete"
  exit 0
}

cleanup() {
  clearLock "$windrose_server_pidfile"
}

shutdown() {
  debug "Received signal to shut down windrose-server"
  if [ $windrose_server_pid -eq -1 ]; then
    debug "windrose server is not running yet - aborting startup"
    exit
  fi
  info "Shutting down windrose server with PID $windrose_server_pid"
  kill -$kill_signal $(ps axww | grep '\\[e]nshrouded_server' | awk '{print $1}')
  shutdown_timeout=$(($(date +%s) + timeout))
  while [ -d "/proc/$windrose_server_pid" ]; do
    if [ "$(date +%s)" -gt $shutdown_timeout ]; then
      shutdown_timeout=$(($(date +%s) + timeout))
      warn "Timeout while waiting for server to shut down - sending SIG$kill_signal to PID $windrose_server_pid"
      kill -$kill_signal $windrose_server_pid
      case "$kill_signal" in
      INT)
        kill_signal=TERM
        ;;
      *)
        kill_signal=KILL
        ;;
      esac
    fi
    debug "Waiting for windrose Server with PID $windrose_server_pid to shut down"
    sleep 6
  done
}

trap shutdown SIGINT SIGTERM
main
